### ISSUE TITLE
Two columns have name nfunction

### ISSUE THREAD

**Issue by jwalden** [dspinellis/cqmetrics#12]
Two of the column headers have the same name "nfunction" and there is also a column named "nfunction2", all of which contain the function count. The duplicate name produces an error for some TSV parsers. While removing the duplicate columns would break scripts that parse data out of qmcalc by column position, renaming the second "nfunction" column to "nfunction1" would prevent the error and likely not cause any problems.

**Comment by dspinellis** [comment]
It must have been an oversight, because another duplicate column is named as `nfunction2`.  I renamed the duplicate one `function3`.
