### ISSUE TITLE
cqmetrics prints empty strings instead of zeros for metrics in some cases

### ISSUE THREAD

**Issue by jwalden** [dspinellis/cqmetrics#18]
When running qmcalc on win2posix/sys/types.h from the BSDCoreUtils repository (https://github.com/DiegoMagdaleno/BSDCoreUtils), qmcalc prints several fields like statement_nesting_min as blanks instead of zeros. This particular file contains no statements. Here is the output of the command piped through "cat -vet" to show sequences of tabs with no numbers between them.

> qmcalc win2posix/sys/types.h | cat -vet
133^I9^I0^I13.7778^I13^I31^I9.56589^I1^I1^I0^I^I^I^I^I^I0^I0^I1^I0^I0^I0^I0^I0^I0^I0^I0^I0^I0^I0^I0^I0^I0^I0^I0^I0^I0^I2^I0^I0^I0^I0^I0^I1^I30^I30^I30^I30^I0^I1^I1^I1^I1^I1^I0^I7^I8^I10^I11^I11^I1.30931^I6^I8^I9.83333^I10.5^I11^I1.34371^I1^I4^I4^I4^I4^I0^I0^I1^I0^I0^I0^I0^I0^I0^I1^I0^I0^I0^I0^I0^I0^I0^I0^I0^I0^I0^I1^I0^I3^I1^I0^I0^I0^I1^I0^I0^I0^I0^I0^I0^I0^I0^I3^I0^I1$

The full text of types.h is given below:

>enum {
>    DEV_NULL,
>    DEV_ZERO,
>    DEV_URANDOM,
>    NOT_DEVICE = -1
>};
>
>#define DEFAULT_UID 4095
>#define DEFAULT_GID DEFAULT_UID

**Comment by dspinellis** [comment]
The empty fields correspond to values of descriptive statistics (min, mean, median, max, standard deviation) regarding statement nesting, Halstead complexity, cyclomatic complexity, indentation spacing, etc. The count number is reported as zero (e.g. zero functions), but the rest are left empty to signify N/A values.
