### ISSUE TITLE
Incorrect metrics result from different brace positions at start of function

### ISSUE THREAD

**Issue by jwalden** [dspinellis/cqmetrics#9]
The software incorrectly computes metrics such as nstatement and cyclomatic_max when C code is formatted in certain ways.  In the attached ZIP file are two copies of d1_lib.c, one from OpenSSL 0.9.8ze and the other from OpenSSL 0.9.8zf, along with qmcalc output for both.  While the two files are approximately the same size (518 and 508 lines respectively), the number of statements computed for the 0.9.8ze version is 9, while the number of statements computed for the 0.9.8zf version is 169.  Several other metrics like cyclomatic complexity show similar differences between the two files. Large differences in these metrics can be found in all .c files in those two versions of OpenSSL.

When measuring size of these two files  with cloc and sloccount, the results are quite similar. For example, cloc sees 75 blank lines, 92 comments, 351 lines of code in the 0.9.8ze version and 74 blank lines, 98 comment lines, and 336 lines of code in the 0.9.8zf version. 

The only major difference between the two files is formatting. The OpenSSL project reformatted code between the 0.9.8ze and 0.9.8zf releases. Functions in the 0.9.8e code have the beginning and end curly braces on their own lines preceded by a tab, while functions in the 0.9.8f code place curly braces at the beginning of lines. There are many indentation differences between files in the two versions too.

[example-file.zip](https://github.com/dspinellis/cqmetrics/files/2185877/example-file.zip)

**Comment by dspinellis** [comment]
Thank you!  Can you please post a minimal example demonstrating the issue?  A fix through a pull request would be even more appreciated.

**Comment by jwalden** [comment]
I attached the requested minimal examples. The ZIP contains 4 versions of Hello World, one with the braces at the beginning of the lines which is counted correctly, and the other 3 with different variants of brace placement, none of which are counted correctly. Running qmcalc registers 1 function and 1 statement for the good example, and 0 functions and 0 statements for the 3 bad examples.

[brace-miscounts-minimal-examples.zip](https://github.com/dspinellis/cqmetrics/files/2189606/brace-miscounts-minimal-examples.zip)

**Comment by jwalden** [comment]
I found the section of code in calculate_metrics_switch() that identifies function beginnings. It begins with a comment that explains the problem, as the heuristic for identifying the start of a function is a { in the first column.

// Heuristic: functions begin with { at first column
if (bol.at_bol()) {
    current_depth = 0;
    qm.begin_function();
    in_function = true;
    nesting.reset();
 }

Changing bol.at_bol() to bol.at_bol_space()  produces correct function and statement counts for my two minimal examples that have spaces or tabs before the brace, which verifies that the problem is happening in this test. However, this change is insufficient to fix the problem. It counts any blocks started by braces on a line as functions, resetting the nesting depth counter, which causes it to fail testIndentationGnuBrace when running "make test", so we need to combine this test with a test for the absence of a previous keyword that could start a block.

Another issue is that this fix would not detect K&R style functions where the { is on the same line as the brace.

**Comment by dspinellis** [comment]
Nice explanation!  Exactly, brace at BOL is an accurate heuristic for identifying functions using the style

```
foo()
{
```

For the cases you give, the best I can think of is considering the scope level as out of function when non-`#` text appears at the beginning of the line, and then using the first brace top mark the function's beginning.

**Comment by jwalden** [comment]
My current solution replaces the bol.at_bol() conditional test with

bol.at_bol_space() && ! in_function &&  ! in_struct && ! in_union && ! in_toplevel_assignment

which I think accounts for the possible reasons to see a brace at the beginning of a line in C.

**Comment by dspinellis** [comment]
Thank you for the suggestion!  But we still don't cover the following, right?

```
int foo() {
    return 42;
}
```

**Comment by jwalden** [comment]
Correct. That's just where I stopped last night.  Removing the bol.at_bol_space() test picks up that style of function, and the change works correctly on all of the minimal examples above.

**Comment by jwalden** [comment]
I've been testing function counts against ctags, and I think the results are correct. It does count code inside of #ifdef 0 blocks which ctags does not, but I think it's reasonable to include such code for software metrics. Even if it's not compiled, it's still there for the programmer to read. Next week, I'll have time to remove my debugging code and send you a final version.

**Comment by dspinellis** [comment]
Good idea to test against *ctags*!  Have you also added support for the `int foo() {` style?

**Comment by jwalden** [comment]
Yes, it will count those functions now too.

**Comment by dspinellis** [comment]
Merged pull request that addresses this issue.
